---
- name: add repo
  command: "yum-config-manager --add-repo={{ docker__repo_url }}"

- name: install docker-ce
  yum:
    name: docker-ce
    state: "{{ docker__installed_state }}"
  
- name: install docker-ce-cli
  yum:
    name: docker-ce-cli
    state: "{{ docker__installed_state }}"

- name: install containerd.io
  yum:
    name: containerd.io
    state: "{{ docker__installed_state }}"
  
- name: Enable service docker
  service:
    name: docker
    enabled: "{{ docker__service_enabled_state }}"  
  notify: restart docker