---
- name: add repo
  command: yum-config-manager --add-repo=https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo

- name: install consul
  yum:
    name: consul
    state: installed
  
- name: Enable service consul
  service:
    name: consul
    enabled: yes
  notify: restart consul