---
- name: add repo
  command: "yum-config-manager --add-repo={{ consul__repo_url }}"

- name: install consul
  yum:
    name: consul
    state: "{{ consul__installed_state }}"
  
- name: add consul script
  template:
    src: consul.sh.j2
    dest: "{{ consul__script_destination }}"
    owner: "consul"
    group: "consul"
    mode: "{{ consul__mode_for_template }}"
  
- name: Enable service consul
  service:
    name: consul
    enabled: "{{consul__service_enabled_state }}"
  notify: restart consul