---
- name: Add the repository for consul
  command: yum-config-manager --add-repo=https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo

- name: Install consul
  yum:
    name: consul
    state: installed
  
- name: Add the consul script
  template:
    src: consul.sh.j2
    dest: /etc/consul.d/consul.hcl
    owner: "consul"
    group: "consul"
    mode: u=rwx,g=r,o=r
  notify: restart consul
  
- name: Enable the consul service
  service:
    name: consul
    enabled: yes
  notify: restart consul