---
#- hosts: all
#tasks:
#- name: install needed tools
#become: true
#become_user: root
#yum:
#state: present
#name:
#- zip
#- unzip
#- epel-release
#- bind-utils
#- vim

- hosts: all
  become: true
  any_errors_fatal: false
  roles:
    - 'software/docker'
    - 'software/consul'
    - 'software/nomad'
