---
#- hosts: all
#tasks:
#- name: install needed tools
#become: true
#become_user: root
#yum:
#state: present
#name:
#- zip
#- unzip
#- epel-release
#- bind-utils
#- vim

- hosts: 'server'
  become: true
  any_errors_fatal: true
  roles:
    - 'software/docker'
    - 'software/consul'
    - 'software/nomad'

- hosts: 'agent1'
  become: true
  any_errors_fatal: true
  roles:
    - 'software/dockerAgent1'
    - 'software/consulAgent1'
    - 'software/nomadAgent1'

- hosts: 'agent2'
  become: true
  any_errors_fatal: true
  roles:
    - 'software/dockerAgent2'
    - 'software/consulAgent2'
    - 'software/nomadAgent2'