# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
		config.vbguest.auto_update = false
        config.vm.box = "centos/7"
        config.vm.hostname = "test-machine"
        config.vm.box_check_update = false
        config.vm.synced_folder ".", "/ansible", disabled: true

        config.vm.provider "virtualbox" do |v|
                v.memory = 512
                v.cpus = 1
        end

        config.vm.provision "ansible" do |ansible|
                ansible.playbook = "ansible/plays/all.yml"
                ansible.config_file = "ansible/ansible.cfg"
        end
end
