# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vbguest.auto_update = false
  config.vm.provision "shell", path: "installAnsible.sh"
  config.vm.box = "centos/7"

  config.vm.define "server" do |server|
    server.vm.hostname = "server"
    server.vm.network "private_network", ip: "192.168.1.2", virtualbox__intnet: "mynetwork"
	
	server.vm.provision "ansible_local" do |ansible|
      ansible.config_file = "ansible/ansible.cfg"
      ansible.playbook = "ansible/plays/server.yml"
      ansible.groups = {
        "servers" => ["server"],
#        "servers:vars" => {"software__content" => "servers_value"}
      }
      ansible.host_vars = {
#        "server" => {"software__content" => "server_value"}
      }
#      ansible.verbose = '-vvv'
    end
  end

  config.vm.define "agent1" do |agent1|
    agent1.vm.hostname = "agent1"
    agent1.vm.network "private_network", ip: "192.168.1.3", virtualbox__intnet: "mynetwork"
	
	agent1.vm.provision "ansible_local" do |ansible|
      ansible.config_file = "ansible/ansible.cfg"
      ansible.playbook = "ansible/plays/agent.yml"
      ansible.groups = {
        "agents" => ["agent1"],
#        "agents:vars" => {"software__content" => "agents_value"}
      }
      ansible.host_vars = {
#        "agent1" => {"software__content" => "agent1_value"}
      }
#      ansible.verbose = '-vvv'
    end
  end

  config.vm.define "agent2" do |agent2|
    agent2.vm.hostname = "agent2"
    agent2.vm.network "private_network", ip: "192.168.1.4", virtualbox__intnet: "mynetwork"
	
	agent2.vm.provision "ansible_local" do |ansible|
      ansible.config_file = "ansible/ansible.cfg"
      ansible.playbook = "ansible/plays/agent.yml"
      ansible.groups = {
        "agents" => ["agent2"],
#        "agents:vars" => {"software__content" => "agents_value"}
      }
      ansible.host_vars = {
#        "agent2" => {"software__content" => "agent2_value"}
      }
#      ansible.verbose = '-vvv'
    end
  end
  
  config.vm.provider :virtualbox do |virtualbox, override|
    virtualbox.customize ["modifyvm", :id, "--memory", 2048]
  end
  
  config.vm.provider :lxc do |lxc, override|
    override.vm.box = "visibilityspots/centos-7.x-minimal"
  end

end