# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vbguest.auto_update = false
	
	config.vm.box = "centos/7"
	config.vm.box_check_update = false
	config.vm.synced_folder ".", "/ansible", disabled: true

	config.vm.define "server" do |server|
	  server.vm.hostname = "server"
	  server.vm.network "private_network", ip: "192.168.1.2", virtualbox__intnet: "mynetwork"

          config.vm.provider "virtualbox" do |v|
            v.memory = 2048
            v.cpus = 1
          end
	end


	config.vm.define "agent1" do |agent1|
	  agent1.vm.hostname = "agent1"
	  config.vm.network "private_network", ip: "192.168.1.3", virtualbox__intnet: "mynetwork"

	  config.vm.provider "virtualbox" do |v|
	    v.memory = 2048
	    v.cpus = 1
	  end
	end


	config.vm.define "agent2" do |agent2|
	  agent2.vm.hostname = "agent2"
	  agent2.vm.network "private_network", ip: "192.168.1.4", virtualbox__intnet: "mynetwork"

	  config.vm.provider "virtualbox" do |v|
	    v.memory = 2048
	    v.cpus = 1
	  end
	end
	  

        config.vm.provision "ansible" do |ansible|
          ansible.playbook = "ansible/plays/all.yml"
          ansible.config_file = "ansible/ansible.cfg"
        end
end
