---
docker_edition: 'ce'
docker_package: "docker-{{ docker_edition }}"
docker_package_state: present

docker_service_state: started
docker_service_enabled: true
docker_restart_handler_state: restarted

docker_yum_repo_url: https://download.docker.com/linux/centos/docker-ce.repo
docker_yum_gpg_key: https://download.docker.com/linux/centos/gpg

docker_group_members: 
  - 'ubuntu'
