---
- name: Add the repository for nomad
  command: yum-config-manager --add-repo=https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    
- name: Install nomad
  yum:
    name: nomad
    state: installed
  
- name: Add the nomad script
  template:
    src: nomad.sh.j2
    dest: /etc/nomad.d/nomad.hcl
    owner: "root"
    group: "root"
    mode: u=rwx,g=r,o=r
  notify: restart nomad
  
- name: Enable the nomad service
  service:
    name: nomad
    enabled: yes
  notify: restart nomad