---
- name: add repo
  command: "yum-config-manager --add-repo={{ nomad__repo_url }}"
    
- name: install nomad
  yum:
    name: nomad
    state: "{{ nomad__installed_state }}"
  
- name: add nomad script
  template:
    src: nomad.sh.j2
    dest: "{{ nomad__script_destination }}"
    owner: "root"
    group: "root"
    mode: "{{ nomad__template_mode }}"
  
- name: Enable service nomad
  service:
    name: nomad
    enabled: "{{ nomad__service_enabled_mode }}"
  notify: restart nomad